spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes: 
      - id: product
        uri: lb://01-PRODUCTS-MS
        predicates:
        - Path=/product-api/**
  application:
    name: CLOUD-API-GATEWAY
server:
  port: 3333
  
  main:
    web-application-type: reactive